spring:
  config:
    import:
      - optional:classpath:secret/db.yml
  application:
    name: mreview
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false
  servlet:
    multipart:
      location: d:/upload
      max-file-size: 10MB
